### PR TITLE
added Keystone 1042 footprint

### PR DESCRIPTION
**Pull request by Shackmeister**
keystone_1042

### CODE REVIEW

**Comment by Shackmeister** [comment]
keystone_18650

**Comment by poeschlr** [comment]
The description field should contain more than just the datasheet link. (Example: Battery holder for 18650 cylindrical cells.)

There is one hole missing.
1042 pdf

**Comment by Shackmeister** [comment]
@poeschlr Hi can you give it another check? :)

keystone_1042

**Comment by poeschlr** [comment]
Looks good now.
Thanks

**Pull request merged**
