### PR TITLE
Keystone aaa

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added 3x footprints for Keystone AAA cell battery holders
- 2466 - http://www.keyelco.com/product.cfm/product_id/1031
- 2468 - http://www.keyelco.com/product.cfm/product_id/1033
- 2479 - http://www.keyelco.com/product.cfm/product_id/1041

### CODE REVIEW

**Comment by pointhi** [comment]
```
checking module: Keystone_2466_1xAAA
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
checking module: Keystone_2468_2xAAA
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
checking module: Keystone_2479_3xAAA
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
```
- Increasing the pad size would also be a good idea
- what about using NTPH Holes for the  mounting holes?

**Comment by SchrodingersGat** [comment]
Done, thanks for spotting this.

**Comment by pointhi** [comment]
- personally, I would move the inner drawings from F.Fab to F.SilkS.
- You could use text labels instead of drawing the characters line per line.
- there are some rounding errors for the ntph pads

**Comment by SchrodingersGat** [comment]
Done. Although, the NPTH holes are not "rounded" as the footprints were originally centered but I had to move them so pin-1 was at the origin. So the locations of the NPTH holes are a bit weird.

**Comment by pointhi** [comment]
you added the 9v battery holder without a courjard and I don't think you have to use normal pads for the mounting holes.

**Comment by SchrodingersGat** [comment]
Ack, didn't mean to add the 9V part.

**Comment by pointhi** [comment]
thanks for you contribution

**Pull request merged**
