### PR TITLE
Bulgin: Added BX0036 Type C Battery Holder

### PR DESCRIPTION
**Pull request by myfreescalewebpage**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @myfreescalewebpage thanks for your contribution. Check out the discussion of naming conventions for these parts here -> https://github.com/KiCad/Battery_Holders.pretty/pull/2

**Comment by myfreescalewebpage** [comment]
No problem, but what is the final choice ? I have seen you are discussing about several possibilities in https://github.com/KiCad/Battery_Holders.pretty/pull/2.

**Comment by SchrodingersGat** [comment]
I think we have come to a decision :)

**Comment by myfreescalewebpage** [comment]
Looking at the last comments, I can rename my footprint to "Bulgin_BX0036_TypeC". Is it ok for you ?

**Comment by SchrodingersGat** [comment]
I think that "Bulgin_BX0036_1xC" would be appropriate.

**Comment by myfreescalewebpage** [comment]
Done.

**Comment by pointhi** [comment]
- I think you could remove the copper ring from the NTPH Pads
- I would remove the `-Cell` part of the footprint name, to build up a consistent naming scheme
- your pins are not exactly positionized as described on the datasheet (http://www.mouser.com/ds/2/57/BattHolders_2010-6900.pdf)
- There are no polarity markings. I would suggest using a rectacular pad (1) and silk screen annotations.

**Comment by myfreescalewebpage** [comment]
Thanks for review.
Done.

**Review by pointhi — CHANGES_REQUESTED** [review]
- use 0.5mm courtjard distance (https://github.com/KiCad/Battery_Holders.pretty/pull/2#issuecomment-237977755)
- I didn't meaned to write an 1 on the positive pin, more like it should be placed near pin 1. Sorry, I didn't clarify it enough. I suggest to use a `+` sign as done with the other battery holders
- It would be a good idea to remove the Silkscreen from the Pads
-  according to KLC, silk screen should be fully visible after assembly

the rest looks fine

**Comment by myfreescalewebpage** [comment]
Use of 0.5mm courtjard distance: upgraded
Use "+" instead of "1" : upgraded.
Silkscreen: I do not understand, it is not on the pads... I have moved the REF label maybe it is what you are expecting ? ... Screenshot below.

capture

**Comment by myfreescalewebpage** [comment]
Up ?

**Comment by SchrodingersGat** [comment]
Regarding the "silkscreen on pads" issue -> Go to the pad-options for each of the 4 pads, and uncheck the "Silkscreen" layer.

**Comment by evanshultz** [comment]
@myfreescalewebpage Will you be able to finish and update this PR?

**Comment by poeschlr** [comment]
@SchrodingersGat Why does travis not report missing fab elements for this repo?

@myfreescalewebpage the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) did change a bit since your last commit.

Please add the true part outline to the fab layer (the outline on silk should be outside of the part itself.)
Add a second reference to the fab layer
The documentation field should hold some information about the part. (not only the link to the datasheet)

The 3d settings should be filled out: 
- Path: ${KISYS3DMOD}/library_name.3dshapes/footprint_name.wrl
- scale: 1,1,1
- offset: 0,0,0
- rotation: 0,0,0

**Comment by SchrodingersGat** [comment]
The Travis log indicates that the KLC script didn't run at all..

`fatal: Invalid symmetric difference expression 484bbd7cdc8beb071b01c6f79ff4fb7c76ddfd06...581bba7b5709b0c4a1c0d9480653272d4be21d23`

**Comment by evanshultz** [comment]
@myfreescalewebpage Please see the comments above. There is salient feedback on how to bring this PR to completion. Will you be able to finish it off?

**Comment by evanshultz** [comment]
Updated PR submitted at https://github.com/KiCad/Battery_Holders.pretty/pull/12. Once that one is merged this PR can be deleted.

**Comment by SchrodingersGat** [comment]
#12 has been merged, so closing this PR

**Pull request closed without merging**
