### PR TITLE
adding MS621F coin battery footprint

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
hi1

thanks!

1. please move origin:
2017-02-08 20_20_25-footprint editor no active library
2. rename to `Seiko_MS621F` to match other names in this lib

Best,
JAN

**Comment by jkriege2** [comment]
nice work!

Before merging I have one short question: The pads have exactly the same width as the metal strips from the battery ... is that OK, or should they be a bit broader? Did you find any manufacturer recommendations for the pad size (I didn't find any)?

Best,
JAN

**Comment by jeromebeguin** [comment]
I didn't find any as well, But I can make them a bit wider.

**Comment by jkriege2** [comment]
not sure ... I would make them a bit wider, then it's for sure easier to also solber them by hand ... but then: You want t use it, so make it in a way that works for you and it should be fine for most People ;-)

Just let me know when I should merge ...

JAN

**Comment by jeromebeguin** [comment]
It should be ok now. 

Best 

Jérôme

**Comment by jkriege2** [comment]
nice work!
JAN

**Pull request merged**
