### PR TITLE
[enh] add first batch of smisioto.no-ip.org footprints

### PR DESCRIPTION
**Pull request by pointhi**
Footprints downloaded from: http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm and made KLC comply. (with exception of two through hole holders, which violate rule 6.3, but there are completly symetrical so I think the current design is more meaningfull)

There is currently no PR for the 3d-files, but they can easily created by downloading the 3d-files from smisioto.no-ip.org and renaming them a little bit.
## 

keystone_2993
keystone_2993_3d
## 

keystone_3000
keystone_3000_3d
## 

keystone_3001
keystone_3001_3d

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@pointhi you have clearly put a lot of effort into these, they look really good :)

Regarding naming convention for this repo, I would suggest the following:

BatteryHolder_CellType_Manufacturer-PN.kicad_mod

e.g.

BatteryHolder_12mm_Keystone-3000.kicad_mod

Otherwise there's no way of determining (from the footprint name) the purpose of each footprint.

My existing footprints (I have yet to issue PRs for them) -> https://github.com/SchrodingersGat/Battery_Holders_Old.pretty

Although for mine, "CoinCell" should be changed to something more useful.

**Comment by pointhi** [comment]
hm, I think `BatteryHolder` would create the same redundancy as previous for the `Connectors` repositories. What about `Manufacturer_PN_CellType.kicad_mod` which would also be more consistent?

**Comment by SchrodingersGat** [comment]
Good point(hi). 

So for the example as above:
1. Keystone-3000_CoinCell-12mm
2. Keystone-3000_12mmCoinCell
3. Keystone-3000_12mm
4. Some other option?

**Comment by SchrodingersGat** [comment]
The issue with leaving out "batteryholder" in the name is that the battery schematic symbol can't use a FP-filter to associate with these footprints...

**Comment by pointhi** [comment]
https://github.com/KiCad/kicad-library/issues/368#issuecomment-177514422

**Comment by SchrodingersGat** [comment]
Is this suggesting that the "search by keyword" functionality already exists in the footprint association window? If so then let's proceed without the BatteryHolder_ prefix

**Comment by pointhi** [comment]
I would suggest, every battery holder has to contain at least the keywords `battery` (and better also `holder`)

`Keystone-3000_CoinCell-12mm` seems for me the best naming solution

**Comment by SchrodingersGat** [comment]
I'm happy with that :)

**Comment by pointhi** [comment]
@SchrodingersGat 

I updated the footprint names like: `Keystone_3000_1x12mm-CoinCell`

I left `Keystone_2993` as it be, because I don't know how to name it well (It's a negative CoinCell Contact)

**Comment by CarlPoirier** [comment]
I'd consider these as connectors and use a 0.5mm courtyard.

**Comment by pointhi** [comment]
@CarlPoirier changed as mentioned

**Comment by SchrodingersGat** [comment]
For the 3008 and 3009 parts, it appears that the 'tab' at the back of the holder is wider than it should be?

http://www.keyelco.com/product-pdf.cfm?p=787

tab

The tab drawn in your components is a lot wider than the drawing suggests.

**Comment by pointhi** [comment]
you'r true. It seems like smisioto simply resized the footprint instead of drawing it correctly. I think there are other problems with the shape too, (front part of the footprint) but I don't have the mesasurements to fix them.

**Comment by SchrodingersGat** [comment]
Sweet, that was the only thing I could spot :)

**Pull request merged**
